### ISSUE TITLE
2.1 Modeling keywords

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#2]
I have a question not related to code but the paper,
I hope I get the answer of that,
In part 2.1 of the paper, column2, formula(7)

the bold difference between the two formula is(ignoring B) the first formula has Log and the second one which you reasoned will give broader topics does not have Log,

May I ask you explain how you come up with this?
I mean how you can conclude that the first formula gives more specific and the second broader while the only difference is Log?

Thank you so much, sorry if my question is not a coding issue and maybe kind of naive,

**Comment by JohnTailor** [comment]
Example: 
Hurlington is a specific sports (in Ireland), whenever you see it you know the topic must be sports, but only experts on sports know it. Football is a sports but it occurs in many other topics, eg. celebrities (football stars), buildings (football stadiums), thus when you see it you cannot be sure that the topic is really sports, but everyone knows football.
Therefore, for non-experts football is a better keyword for sports since they know it (the word is very frequent in general), but football is worse for classification (since the topic is non-unique) compared to hurlington. Hurlington is good for classification but maybe a worse keywords for sports, since it is not known by many (eg. a rarely occuring word) The formula captures this intuition:

Topic sports: football occurs 64 times, hurlington occurs 4 times
Hurlington might only occur in sports thus have concentration 1.  Football might occur in other topics thus have a concentration of 0.25.
Hurlington has ~log2(4)*1=2 for classification (should be normalized) and 4*1 for human = 4
Football has log2(64)*0.25=1.5  and 64*0.25=16

**Comment by un-lock-me** [comment]
Thank you so much, I forgot to feedback on your explanations, It was very useful
